name: CI Backend Nest.js

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

defaults:
  run:
    working-directory: ./rentease-backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: ./rentease-backend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm run test
